
on:
  push:
    branches: [ "**" ]
    paths:
        -".github/workflows/security.yml"

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write
      actions: read
      packages: write
      security-events: write  

      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Debug Logging
        run: |
          echo "GITHUB_ACTIONS_RUNNER_DEBUG=1" >> $GITHUB_ENV
          echo "GITHUB_ACTIONS_STEP_DEBUG=1" >> $GITHUB_ENV

      - name: Enable Security Settings
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"security_and_analysis": {
                "code_scanning": {"status": "enabled"},
                "secret_scanning": {"status": "enabled"},
                "secret_scanning_push_protection": {"status": "enabled"},
                "dependabot_security_updates": {"status": "enabled"},
                "dependabot_alerts": {"status": "enabled"},
                "validity_check": {"status": "enabled"}
                }
            }'

      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
            path: '.'
            project: 'MyProject'
            format: 'JSON'
            out: 'dependency-check-report.json'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"



      - name: Verify Security Settings
        run: |
          curl -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/security-advisories

      
      - name: Debug Repository Info
        run: |
          curl -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}

