
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '15 21 * * 5'

jobs:
  security-checks:
    name: Security Checks
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write
      actions: read
      packages: write
      security-events: write  # Required to modify repository security settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔹 Enable Debugging for better error messages
      - name: Enable Debug Logging
        run: |
          echo "GITHUB_ACTIONS_RUNNER_DEBUG=1" >> $GITHUB_ENV
          echo "GITHUB_ACTIONS_STEP_DEBUG=1" >> $GITHUB_ENV

      # 🔹 Ensure Code Scanning is Enabled
      - name: Enable Security Settings
        run: |
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} \
            -d '{"security_and_analysis": {
                "code_scanning": {"status": "enabled"},
                "advanced_security": {"status": "enabled"},
                "secret_scanning": {"status": "enabled"},
                "secret_scanning_push_protection": {"status": "enabled"},
                "dependabot_security_updates": {"status": "enabled"},
                "dependabot_alerts": {"status": "enabled"},
                "validity_check": {"status": "enabled"}
                }
            }'

      # 🔹 Dependency Check (Fixing 'Resource not accessible' error)
      - name: Run Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
            path: '.'
            project: 'MyProject'
            format: 'JSON'
            out: 'dependency-check-report.json'
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAT }}

      # 🔹 Initialize CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript

      # 🔹 Autobuild for CodeQL
      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      # 🔹 Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript-typescript"


      # 🔹 Verify Security Settings
      - name: Verify Security Settings
        run: |
          curl -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/security-advisories

      # 🔹 Debug Repository Details
      - name: Debug Repository Info
        run: |
          curl -H "Authorization: token ${{ secrets.MY_GITHUB_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}
